name: Build and Deply

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Build Gatsby site
      run: |
        npm install
        npm install -g gatsby-cli
        CI=flase gatsby build
        env:
          spaceId: ${{secrets.SPACE_ID}}
          accessToken: ${{secrets.CONTENTFUL_TOKEN}}

    - name: Install Surge
      run: npm install -g surge
      
    - name: Deploy to Surge
      run:  surge ./public https://blogbyusama.surge.sh/ --token ${{secrets.TOKEN}}
  
